### PR TITLE
client: fix marshaling of int64 type

### LINKED ISSUE #221: wireguard endpoint port and keepalives don't work
System version 7.13.4
provider version  = "0.15.0"
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to mikrotik_interface_wireguard_peer.default, provider "provider[\"registry.terraform.io/ddelnano/mikrotik\"]" produced an unexpected new
│ value: .endpoint_port: was cty.NumberIntVal(13251), but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to mikrotik_interface_wireguard_peer.default, provider "provider[\"registry.terraform.io/ddelnano/mikrotik\"]" produced an unexpected new
│ value: .persistent_keepalive: was cty.NumberIntVal(20), but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### PR DESCRIPTION
**Pull request by maksym-nazarenko**
Closes #221

### CODE REVIEW

**Comment by ddelnano** [comment]
Thanks for fixing this @maksym-nazarenko!

**Review by ddelnano — APPROVED** [review]

**Comment by ddelnano** [comment]
Hm, the build for the latest RouterOS seems to be failing. Upon looking at it briefly it seems like doesn't seem related to your change, but I wasn't able to dig into it right now.

I did notice that the evilfreelancer/docker-routeros project has automated creating new docker images (https://github.com/EvilFreelancer/docker-routeros/pull/20). I wonder if it's also failing on master and is independent of your change.

**Comment by maksym-nazarenko** [comment]
created #224 
It is and issue with upstream RouterOS container

**Comment by ddelnano** [comment]
Thanks for investigating. No concern on my end with proceeding to merge.

**Pull request merged**
