### PR TITLE
Add mikrotik_ipv6_address resource

### PR DESCRIPTION
**Pull request by jmbaur**
Tested against RouterOS 7.1.1

### CODE REVIEW

**Comment by ddelnano** [comment]
@jmbaur thanks for the contribution! It seems the CI job is failing due to an issue with terraform-json. It seems we are using [v0.12.0](https://github.com/ddelnano/terraform-provider-mikrotik/blob/52918b8cd379db0b7da1c7820c92e65a1b24a9ed/go.sum#L196) and that seems to be the impacted version from the [google searching](https://github.com/gruntwork-io/terratest/issues/943) I did.

If you could update that dependency, that should make the test suite happier so I can review this. Let me know if you are ok to fix that yourself, otherwise I can fix master and let you rebase.

**Comment by ddelnano** [comment]
@jmbaur I've fixed master in #56 so please rebase your change.

**Comment by jmbaur** [comment]
> @jmbaur I've fixed master in #56 so please rebase your change.

Thank you! Just rebased on those changes

**Comment by jmbaur** [comment]
@ddelnano Got the testing setup working locally, if you are alright approving this CI run :)

**Comment by ddelnano** [comment]
@jmbaur the new tests you added are guaranteed to fail on any RouterOS version <  7. I've started #59 to address this.

**Comment by jmbaur** [comment]
@ddelnano what is the routeros implementation causing it to fail on versions < 7? Is it worth adding v7 to the testing matrix?

**Comment by ddelnano** [comment]
@jmbaur RouterOSv7 is being tested. It corresponds to the third build (latest docker tag). This is because v7 wasn't officially released when we set up our CI, so we used the bleeding edge docker image version to correspond to v7.

For some reason when the first two builds fail, it doesn't attempt to run the v7 build (which would have passed). I needed to add the code to appropriately skip the tests you added from the first two builds.

It seems v7 was released at the end of 2021? If that's the case, we should see if the docker image we use has a tag for v7 and add that to the test matrix.

**Comment by jmbaur** [comment]
Closing in favor of #59

**Comment by jmbaur** [comment]
@ddelnano The latest tag I am seeing is`7.1beta6`, released 7 months ago

**Pull request closed without merging**
