### PR TITLE
Refactor/resource firewall filter

### PR DESCRIPTION
**Pull request by maksym-nazarenko**

### CODE REVIEW

**Review by ddelnano — APPROVED** [review]
Exciting to see the final legacy resources migrated to the plugin framework! Thanks for moving so quickly through these and all the great scaffolding work that made this transition easier.

**Comment by maksym-nazarenko** [comment]
I'm really enjoying contributing to this project ;)

**Comment by teadur** [comment]
kube-clouds fork seems to have way fancier firewall, maybe the option set could be migrated to this provider ?
https://github.com/kube-cloud/terraform-provider-mikrotik/blob/master/client/firewall_rule.go
To i understand correctly that neither of them support ipv6 ?

**Comment by maksym-nazarenko** [comment]
@teadur the resources were created with `minimal option set` in mind, as complete support requires much more work.
If you think there are missing parts, which could help you, feel free to create an issue with such request - I'll be glad to evaluate it.

**Pull request merged**
