### PR TITLE
Client/interface list members

### LINKED ISSUE #77: [client] Add support for interface list members managing
Mikrotik resource documentation: https://wiki.mikrotik.com/wiki/Manual:Interface/List#Members
Sub menu in CLI: `/interface list member`
Script example for complete setup:
```
/interface list add name="LAN" comment="LAN devices"
/interface list member add list="LAN" interface="vlan100"
```

### PR DESCRIPTION
**Pull request by maxim-nazarenko**
Closes #77

### CODE REVIEW

**Comment by maxim-nazarenko** [comment]
hey @ddelnano, sorry for such 'unclean' PRs with code duplication like this (duplicated InterfaceList) but I had to branch-off of #94 to have it available in tests. (it would take too long to sync on that - I will rebase this one, once the required code is merged in master)

**Comment by ddelnano** [comment]
No problem, you should be good to rebase and then we can get this one merged as well.

**Comment by maxim-nazarenko** [comment]
rebased and ready for review

**Comment by ddelnano** [comment]
Sorry for the delay on this one.

**Pull request merged**
